# Add this to configuration.yaml for sensor.

sensor:
- platform: tibberprice
  url: "https://api.tibber.com/v1-beta/gql"
  token: "*YOUR API TOKEN HERE*"
  name: "Tibber Price"


# Includes the template file that has the declarations for sensors with time until cheapest hours in 12h and 24h. 
# UPDATE: Moved templates to separate folder. 
template: !include_dir_merge_list templates/
